### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by lishaduck** [ParkerH27/Gpa_Calculator_Public#1]
Again,

> Now that [PSDTools/GPA_Calculator](https://github.com/PSDTools/GPA_Calculator) exists, should this whole repo be archived/moved/deleted?

Personally, I think moved and archived seems reasonable. Keeps everything in one place, and shows which one is the current one. And fewer duplicate GH Pages sites.

**Comment by lishaduck** [comment]
You want these left as-is, correct, @ParkerH27?

**Comment by PetalCat** [comment]
Yes, I will deal with it at a later date...
